AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ProcessKvsRecording

  Sample SAM Template for ProcessKvsRecording

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  ProcessKvsRecording:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ProcessKvs
      Handler: ProcessKvs.ProcessKvsLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 300
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AmazonKinesisVideoStreamsReadOnlyAccess
        - AmazonKinesisReadOnlyAccess
        - Statement:
          - Sid: UpdateAmazonConnectContactAttributes
            Effect: Allow
            Action:
              - connect:UpdateContactAttributes
            Resource: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/0986d350-0ebf-46ed-8c88-db4b40e93690/contact/*'
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          REGION: us-west-2
          RECORDINGS_BUCKET_NAME: freewine-connect-voicemail-us-west-2
          RECORDINGS_KEY_PREFIX: recordings/
          START_SELECTOR_TYPE: FRAGMENT_NUMBER
          DDB_TABLE: ConnectCallRecording
          CLOUDFRONT_DOMAIN: https://xxxxxxxxx.cloudfront.net

Outputs:
  ProcessKvsRecording:
    Description: "Lambda Function ARN"
    Value: !GetAtt ProcessKvsRecording.Arn
  ProcessKvsRecordingIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt ProcessKvsRecordingRole.Arn
