AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Process call Recordings of Amazon Connect

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  S3BucketName:
    Type: String
    Description: Recordings Bucket Name
  S3BucketPrefix:
    Type: String
    Default: recordings/
    Description: Recordings Key Prefix, such as recordings/
  CloudFrontDomain:
    Type: String
    Description: CloudFront Distribution

Resources:
  ProcessKvsRecording:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ProcessKvs
      Handler: ProcessKvs.ProcessKvsLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 300
      Policies:
        - AmazonKinesisVideoStreamsReadOnlyAccess
        - AmazonKinesisReadOnlyAccess
        - Statement:
            - Sid: AmazonS3Access
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::${S3BucketName}/${S3BucketPrefix}*'
        - Statement:
          - Sid: UpdateAmazonConnectContactAttributes
            Effect: Allow
            Action:
              - connect:UpdateContactAttributes
            Resource: !Sub 'arn:${AWS::Partition}:connect:${AWS::Region}:${AWS::AccountId}:instance/*/contact/*'
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          REGION: !Ref AWS::Region
          RECORDINGS_BUCKET_NAME: !Ref S3BucketName
          RECORDINGS_KEY_PREFIX: !Ref S3BucketPrefix
          START_SELECTOR_TYPE: FRAGMENT_NUMBER
          CLOUDFRONT_DOMAIN: !Ref CloudFrontDomain

Outputs:
  ProcessKvsRecording:
    Description: "Lambda Function ARN"
    Value: !GetAtt ProcessKvsRecording.Arn
  ProcessKvsRecordingIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt ProcessKvsRecordingRole.Arn
